### ISSUE TITLE
Set Kanban board

### ISSUE THREAD

**Issue by ShiroYaksha90** [ShiroYaksha90/recipe-app#10]
Hi, we are a team of two members @ShiroYaksha90 @Roland-Ntwali  and in this issue, we created :
- Kanban board
- All the cards for the requirements of the projects
- Assign tasks to each team member 
- [Here is the link to our repo](https://github.com/ShiroYaksha90/recipe-app)

**Comment by addod19** [comment]
## Hi @Roland-Ntwali and @ShiroYaksha90, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
- [ ] Link to the Kanban board added 👍 
- [ ] Information about the number of people in the team included 🚀 
- [ ] Tasks are assigned to team members 🎆 


## Required Changes ♻️
_Check the comments under the review._
- [ ] It would be better if we assign points to each member, let us ensure the points are distributed in a fair manner
- [ ] Some of the task lacks descriptions, for example; 1. Login and registration page, built with devise 2. Make sure there are no N+1 queries happening 3. Write unit and integration test 4. Create a navigation menu that allows users to open all pages created
- [ ] It would be better if we add the column “In Review” to the board to make it complete


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by TedLivist** [comment]
## STATUS: APPROVED ✔️ ✔️

Hi @ShiroYaksha90 and @Roland-Ntwali,

✔️ Tasks are complete and well assigned

Your project is complete!  There is nothing else to say other than... it's time to go ahead with the project :shipit: 
Congratulations! 🎉

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ShiroYaksha90** [comment]
@TedLivist @addod19 Thank you and have a pleasant day
